import express from 'express';
import { sameInstansi } from './auth.js';
const MANAGERS=new Set(['ADMIN','SUPERADMIN','KEPALA','SEKRETARIS','KABID','IRBAN']);
const ok=(res,data={})=>res.status(200).json({ok:true,...data});const fail=(res,s,m)=>res.status(s).json({ok:false,message:m});
const admin=req=>MANAGERS.has(String(req.user?.role||'').toUpperCase());
function scope(req,inst){const x=inst||req.user?.instansi_id;return {inst:x,allowed:sameInstansi(req.user,x)};}
export function createOvertimeRouter({query}){const r=express.Router();
 r.get('/penugasan',async(req,res)=>{try{const {inst,allowed}=scope(req,req.query.instansi_id);if(!allowed)return fail(res,403,'Forbidden');const limit=Math.min(Math.max(parseInt(req.query.limit||'100',10)||100,1),500);const p=[];let sql='SELECT * FROM penugasan WHERE instansi_id=$1';p.push(inst);if(req.query.created_by_nip){sql+=' AND created_by_nip=$2';p.push(String(req.query.created_by_nip));}else if(req.query.nip&&req.query.nip!=='all'){sql+=` AND nip=$${p.length+1}`;p.push(String(req.query.nip));}sql+=` ORDER BY tanggal DESC LIMIT $${p.length+1}`;p.push(limit);const rows=(await query(sql,p)).rows;return ok(res,{rows,data:rows});}catch(e){console.error('[penugasan/list]',e);return fail(res,500,'Gagal memuat penugasan.');}});
 r.post('/penugasan',async(req,res)=>{try{if(!admin(req))return fail(res,403,'Forbidden');const b=req.body||{};const {inst,allowed}=scope(req,b.instansi_id);if(!allowed)return fail(res,403,'Forbidden');let row;if(b.id){row=(await query(`UPDATE penugasan SET status=$1,bukti=$2,lat_pengerjaan=$3,lon_pengerjaan=$4,instansi_id=$5 WHERE id=$6 RETURNING *`,[b.status||'',b.bukti||b.bukti_base64||'',Number(b.actual_lat)||0,Number(b.actual_lon)||0,inst,String(b.id)])).rows[0];}else{row=(await query(`INSERT INTO penugasan (user_id,nama,nip,tanggal,lat,lon,keterangan,created_by,created_by_nip,radius,instansi_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[String(b.user_id||''),String(b.nama||''),String(b.nip||''),String(b.tanggal||''),Number(b.lat)||0,Number(b.lon)||0,String(b.keterangan||''),String(b.created_by||req.user.id),String(b.created_by_nip||req.user.nip||''),Number(b.radius)||100,inst])).rows[0];}if(!row)return fail(res,404,'Penugasan tidak ditemukan.');return ok(res,{data:row,message:'Penugasan berhasil disimpan.'});}catch(e){console.error('[penugasan/save]',e);return fail(res,500,'Gagal menyimpan penugasan.');}});
 r.get('/lembur',async(req,res)=>{try{const {inst,allowed}=scope(req,req.query.instansi_id);if(!allowed)return fail(res,403,'Forbidden');const nips=String(req.query.nips||req.query.nip||'').split(',').map(x=>x.trim()).filter(Boolean);if(!nips.length)return ok(res,{data:[],rows:[]});const p=[nips, String(req.query.dari||''),String(req.query.sampai||'')];const rows=(await query(`SELECT l."NIP" AS nip,l."Nama" AS nama,l."Tanggal" AS tanggal,MIN(CASE WHEN UPPER(l."Jenis Absen") LIKE '%MASUK%' THEN l."Jam" END) AS jam_masuk,MAX(CASE WHEN UPPER(l."Jenis Absen") LIKE '%PULANG%' THEN l."Jam" END) AS jam_pulang,MAX(l."Ket") AS status_absen,MAX(CAST(p.id AS TEXT)) AS is_tugas,MAX(p.keterangan) AS tugas_detail,MAX(CASE WHEN UPPER(l."Jenis Absen") IN ('SAKIT','TUGAS','IZIN','CUTI','TUBEL') THEN UPPER(l."Jenis Absen") END) AS keterangan_status FROM "Log_Absen" l LEFT JOIN penugasan p ON l."NIP"=p.nip AND l."Tanggal"::text=p.tanggal::text AND p.instansi_id=$4 WHERE l."NIP"=ANY($1::text[]) AND l."Tanggal" BETWEEN $2 AND $3 AND l.instansi_id=$4 GROUP BY l."NIP",l."Nama",l."Tanggal" ORDER BY l."Tanggal" ASC,l."Nama" ASC`,[...p,inst])).rows;return ok(res,{data:rows,rows});}catch(e){console.error('[lembur/get]',e);return fail(res,500,'Gagal mengambil data lembur.');}});
 r.post('/lembur/archive',async(req,res)=>{try{if(!admin(req))return fail(res,403,'Forbidden');const b=req.body||{};const {inst,allowed}=scope(req,b.instansi_id);if(!allowed)return fail(res,403,'Forbidden');await query(`CREATE TABLE IF NOT EXISTS rekap_lembur (id SERIAL PRIMARY KEY, judul TEXT NOT NULL, nomor_surat TEXT, tanggal_dari DATE NOT NULL, tanggal_sampai DATE NOT NULL, tanggal_list TEXT[], pegawai_nips TEXT NOT NULL, pegawai_names TEXT NOT NULL, data_json JSONB NOT NULL, instansi_id TEXT, saved_by_nip TEXT, saved_by_nama TEXT, created_at TIMESTAMP DEFAULT NOW())`);const row=(await query(`INSERT INTO rekap_lembur (judul,nomor_surat,tanggal_dari,tanggal_sampai,tanggal_list,pegawai_nips,pegawai_names,data_json,instansi_id,saved_by_nip,saved_by_nama) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[String(b.judul||''),String(b.nomor_surat||''),b.tanggal_dari,b.tanggal_sampai,Array.isArray(b.tanggal_list)?b.tanggal_list:[],String(b.pegawai_nips||''),String(b.pegawai_names||''),JSON.stringify(b.data_json||[]),inst,String(b.saved_by_nip||req.user.nip||''),String(b.saved_by_nama||'')])).rows[0];return ok(res,{data:row,message:'Rekap lembur berhasil diarsipkan.'});}catch(e){console.error('[lembur/archive/save]',e);return fail(res,500,'Gagal menyimpan arsip lembur.');}});
 r.get('/lembur/archive',async(req,res)=>{try{const {inst,allowed}=scope(req,req.query.instansi_id);if(!allowed)return fail(res,403,'Forbidden');await query(`CREATE TABLE IF NOT EXISTS rekap_lembur (id SERIAL PRIMARY KEY, judul TEXT NOT NULL, nomor_surat TEXT, tanggal_dari DATE NOT NULL, tanggal_sampai DATE NOT NULL, tanggal_list TEXT[], pegawai_nips TEXT NOT NULL, pegawai_names TEXT NOT NULL, data_json JSONB NOT NULL, instansi_id TEXT, saved_by_nip TEXT, saved_by_nama TEXT, created_at TIMESTAMP DEFAULT NOW())`);const p=[];let sql;if(req.query.id){sql='SELECT * FROM rekap_lembur WHERE id=$1 AND instansi_id=$2';p.push(parseInt(req.query.id,10),inst);}else{const limit=Math.min(Math.max(parseInt(req.query.limit||'30',10)||30,1),200);const cols=(req.query.with_data==='true'||req.query.with_data==='1')?'*':'id,judul,nomor_surat,tanggal_dari,tanggal_sampai,pegawai_nips,pegawai_names,instansi_id,saved_by_nip,saved_by_nama,created_at';sql=`SELECT ${cols} FROM rekap_lembur WHERE instansi_id=$1 ORDER BY created_at DESC LIMIT $2`;p.push(inst,limit);}const rows=(await query(sql,p)).rows;return ok(res,{data:rows,rows});}catch(e){console.error('[lembur/archive/list]',e);return fail(res,500,'Gagal memuat arsip lembur.');}});
 r.post('/lembur/archive/delete',async(req,res)=>{try{if(!admin(req))return fail(res,403,'Forbidden');const id=parseInt(req.body?.id,10);if(!Number.isInteger(id))return fail(res,400,'id tidak valid');const {inst,allowed}=scope(req,req.body?.instansi_id);if(!allowed)return fail(res,403,'Forbidden');const row=(await query(`DELETE FROM rekap_lembur WHERE id=$1 AND instansi_id=$2 RETURNING id`,[id,inst])).rows[0];if(!row)return fail(res,404,'Arsip tidak ditemukan.');return ok(res,{message:'Arsip rekap lembur berhasil dihapus.'});}catch(e){console.error('[lembur/archive/delete]',e);return fail(res,500,'Gagal menghapus arsip lembur.');}});
 return r;}
