-- Local schema patch: samakan DB absensi-local-pg dengan kebutuhan native_full
BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Tiga tabel lokal ber-skema lama (harness v6), semua kosong -> drop & bikin ulang
DROP TABLE IF EXISTS auth_sessions;
CREATE TABLE auth_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_token text NOT NULL UNIQUE,
  nip text NOT NULL,
  user_id text,
  role text NOT NULL DEFAULT 'USER',
  instansi_id text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  last_used_at timestamptz,
  is_active boolean NOT NULL DEFAULT true
);
CREATE INDEX idx_sessions_token ON auth_sessions(session_token);
CREATE INDEX idx_sessions_nip_active ON auth_sessions(nip, is_active) WHERE is_active = true;

DROP TABLE IF EXISTS device_sessions;
CREATE TABLE device_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash text NOT NULL UNIQUE,
  device_label text NOT NULL DEFAULT '',
  nip text NOT NULL,
  user_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_used_at timestamptz,
  expires_at timestamptz,
  revoked_at timestamptz,
  is_active boolean NOT NULL DEFAULT true
);
CREATE INDEX idx_device_sessions_hash ON device_sessions(token_hash);
CREATE INDEX idx_device_sessions_active ON device_sessions(user_id) WHERE is_active = true;

DROP TABLE IF EXISTS gps_tracking;
CREATE TABLE gps_tracking (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip text NOT NULL,
  user_id text,
  latitude numeric(10,7) NOT NULL,
  longitude numeric(10,7) NOT NULL,
  horizontal_accuracy numeric(6,1),
  recorded_at timestamptz NOT NULL DEFAULT now(),
  -- ponytail: tanggal_iso generated di-skip (non-immutable di timestamptz, tak ada pembaca)
  device text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_gps_tracking_recorded_at ON gps_tracking(recorded_at);

-- Fungsi session (migration 004) — butuh pgcrypto (gen_random_bytes)
CREATE OR REPLACE FUNCTION clean_expired_sessions() RETURNS void
LANGUAGE plpgsql AS $$
BEGIN
  UPDATE auth_sessions SET is_active = false
  WHERE is_active = true AND expires_at < now();
END; $$;

CREATE OR REPLACE FUNCTION create_session(p_nip text, p_user_id text, p_role text DEFAULT 'USER', p_instansi_id text DEFAULT '')
RETURNS text LANGUAGE plpgsql AS $$
DECLARE v_token text;
BEGIN
  v_token := encode(gen_random_bytes(48), 'hex');
  UPDATE auth_sessions SET is_active = false WHERE nip = p_nip AND is_active = true;
  INSERT INTO auth_sessions (session_token, nip, user_id, role, instansi_id, expires_at)
  VALUES (v_token, p_nip, p_user_id, p_role, p_instansi_id, now() + interval '24 hours');
  RETURN v_token;
END; $$;

-- Tabel hilang: keterangan, dokumen, penugasan (skema = produksi)
CREATE TABLE IF NOT EXISTS ket_temp (
  "ID_Ket" text PRIMARY KEY,
  "ID_Pegawai" bigint REFERENCES user_list(id) ON DELETE CASCADE,
  "Nama" text,
  "NIP" bigint,
  "Tanggal" text,
  "Jam" text,
  "Jenis Absen" text,
  "Status" text,
  "Ket" text,
  "tgl_mulai" text,
  "tgl_selesai" text,
  "drive_link" text,
  instansi_id text DEFAULT 'bapperida',
  request_id varchar(255)
);
CREATE INDEX IF NOT EXISTS idx_ket_temp_instansi ON ket_temp(instansi_id);
CREATE INDEX IF NOT EXISTS idx_ket_temp_nip ON ket_temp("NIP");
CREATE INDEX IF NOT EXISTS idx_ket_temp_pegawai ON ket_temp("ID_Pegawai");
CREATE INDEX IF NOT EXISTS idx_ket_temp_status ON ket_temp("Status");

CREATE TABLE IF NOT EXISTS dokumen_pegawai (
  nip bigint PRIMARY KEY,
  nama_dokumen text NOT NULL,
  jenis text,
  tanggal date,
  instansi_id text DEFAULT 'bapperida',
  link text,
  tambah_oleh text,
  file text
);

CREATE TABLE IF NOT EXISTS penugasan (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  nama text NOT NULL,
  nip text,
  tanggal date NOT NULL,
  lat double precision NOT NULL,
  lon double precision NOT NULL,
  keterangan text,
  created_at timestamptz DEFAULT now(),
  created_by text,
  radius integer DEFAULT 100,
  status text DEFAULT 'AKTIF',
  bukti text,
  lat_pengerjaan double precision,
  lon_pengerjaan double precision,
  created_by_nip text,
  nomor_surat text,
  instansi_id varchar(255) DEFAULT 'bapperida'
);
CREATE UNIQUE INDEX IF NOT EXISTS unique_tugas_per_day ON penugasan(user_id, tanggal);
CREATE INDEX IF NOT EXISTS idx_penugasan_user_date ON penugasan(user_id, tanggal);

-- rekap lembur (migration 010)
CREATE TABLE IF NOT EXISTS rekap_lembur (
  id SERIAL PRIMARY KEY,
  judul TEXT NOT NULL,
  nomor_surat TEXT,
  tanggal_dari DATE NOT NULL,
  tanggal_sampai DATE NOT NULL,
  tanggal_list TEXT[],
  pegawai_nips TEXT NOT NULL,
  pegawai_names TEXT NOT NULL,
  data_json JSONB NOT NULL,
  instansi_id TEXT,
  saved_by_nip TEXT,
  saved_by_nama TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS rekap_lembur_instansi_created_idx ON rekap_lembur (instansi_id, created_at DESC);

-- Kolom user_list untuk core-admin USER_SELECT
ALTER TABLE user_list ADD COLUMN IF NOT EXISTS face_descriptor text;

-- ON CONFLICT (request_id) di POST /api/absen butuh unique index (migration produksi punya)
CREATE UNIQUE INDEX IF NOT EXISTS "Log_Absen_request_id_key" ON public."Log_Absen"(request_id);

-- audit jam client (migration 008)
ALTER TABLE public."Log_Absen" ADD COLUMN IF NOT EXISTS client_jam text;

-- pengaturan: unique index utk ON CONFLICT + seed face/kontrol (005/007)
CREATE UNIQUE INDEX IF NOT EXISTS pengaturan_key_instansi_idx ON pengaturan(key, instansi_id);
INSERT INTO pengaturan (key, value, instansi_id) VALUES
  ('face_liveness_enabled', 'true', 'bapperida'),
  ('face_threshold', '0.55', 'bapperida'),
  ('face_meja_threshold', '0.55', 'bapperida'),
  ('face_liveness_score', '0.40', 'bapperida'),
  ('face_mandatory_nips', '[]', 'bapperida'),
  ('kontrol_absen', '{"enabled":false,"toleransi":15,"times":[{"jam":"10:00","aktif":true}]}', 'bapperida')
ON CONFLICT (key, instansi_id) DO NOTHING;

-- 006: global face_recognition (instansi NULL) sudah tak dipakai
DELETE FROM pengaturan WHERE key = 'face_recognition' AND instansi_id IS NULL;

COMMIT;
