-- ═══════════════════════════════════════════════════════════════
-- MIGRATION 009: Device Sessions untuk Meja Absen
-- ═══════════════════════════════════════════════════════════════
-- Token perangkat disimpan sebagai SHA-256, bukan plaintext seperti auth_sessions.
-- Alasannya umur: session_token hanya 24 jam, sedangkan token Meja bertahan berbulan
-- bulan. Hash dihitung di Node (crypto.createHash), jadi tidak butuh pgcrypto.
--
-- Token asli hanya ditampilkan sekali saat pembuatan (lihat POST /api/auth/devices),
-- jadi kolom ini tidak pernah dikembalikan oleh endpoint mana pun.

create table if not exists device_sessions (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  device_label text not null default '',
  nip text not null,
  user_id text not null,
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  expires_at timestamptz,
  revoked_at timestamptz,
  is_active boolean not null default true
);

create index if not exists idx_device_sessions_hash on device_sessions(token_hash);
create index if not exists idx_device_sessions_active on device_sessions(user_id) where is_active = true;